::: {.card title="tableau"}
# Probability: theory and examples

-   $A_i$ disjoint
-   $m: \Omega \times \mathcal B(\mathcal{S}) \to \bf N$
-   $m: \mathcal B(\mathcal{S}) \to \bf N$

# FPP on IHRGs

-   $\{u_i\}$ disjoint
-   Measure space $(S, \mathcal{S}, \mu)$
-   $(\mathcal{S}, \mathcal{B}(\mathcal{S}), \tilde{\mu})$
-   $m: \mathcal{S} \to \bf N$
-   $\xi^s: \Omega \times$

$\mu$ mean-measure of the process, *i.e.*, \$m $\tilde{\mu}$ mean-measure of the process, *i.e.*,\$\xi\^s(

( {

A u

\*i) \stackrel{\mathrel{*\unico                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

 d  i}) \stackrel{\mathrel{\unic                                                                        

 e  o   

 {x2AEB}}}{\sim} P(\mu(A_i)).\$  d   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              e{x2AEB}}}{\sim} P(\tilde{\mu                                                                        

 Here $A_i$ is fixed so $m(A_i)$ is a random variable.  }

```         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          (   
```

We refer to this as the **Poissonian property**.  

```         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {u_i} =\kappa(s, u_i) \mu(u_i))\$   Here $u_i$ is fixed so \$\xi\^s(   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {u_i})\$ is a random variable.   
```

$\mu(A_i) < \infty \implies$ \$ \tilde{\mu}({u_i}) =\kappa(s, u \_ i ) \mu(u_i) \< \infty \implies\$

$\forall \omega \in \Omega$ , the map below is a measure on $\mathcal{S}$. $\forall \omega \in \Omega$ , the map below is a measure on $\mathcal{S}$. $$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $$ \begin{align*}  \begin{align*}    

 m\_{\omega                                                                                              \xi\_\omega\^s\colon \mat                                                                               

 }  h    

    c    

 colon \mathcal{S} &\rightarrow \bf N\                                                                          al B(\mathcal{S}) &\rightarrow \bf N\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

 S&\mapsto m(\omega, S).  S&\mapsto \xi\_(\omega, s).    

 \end{align*} \\end{align\*} $$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $$ Here $\omega$ is fixed, so $m_{\omega}$ is a measure. Here $\omega$ is fixed, so $\xi_\omega^s$ is a measure.

Let us now describe how one can construct such a map $m$. Let us now describe how one can construct such a map $\xi$. Since $\mu(S) < \infty,$ we can define the following probability measure $\nu := \frac{\mu}{\mu(S)}.$ Since \$\tilde{    

                                                                                                             

 We sample $N \sim P(\mu(S))$ independently of everything else.  mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}(\mathcal S) = \sum\_{i=1}\^n We then sample \$X_1, X_2, \do  \kappa(s, u_i) \mu(u_i) \< \infty\$, we can define the following probability measure \$\nu := \f           

 t r

s a

\stackrel{i.i.d}{\sim} \nu\$. c{\tilde\mu}{\tilde\mu(\mathcal{S})}.\$ All this allows us to finally define $m$ via We also sample $N \sim P(\tilde\mu(\mathcal{S}))$ independently of everything else. \$\$ \begin{align*}  We then sample \$X_1, X_2, \do                                                                         

 m\colon \Omega                                                                                         t    

                                                                                                        s    

    \stackrel{i.i.d}{\sim} \nu.\$    

 times \mathcal{S} &\rightarrow \bf N\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

 (  All this allows us to finally define $\xi$ via    

       

 omega, A)&\mapsto {j \leq N  \$\$    

 (  \begin{align*}    

    \xi\colon \Omega \times \mat                                                                          

 omega): X_j(\omega) \in A}.  h    

 \end{align*}  c omega): X_j(\omega) \in A}. \\end{align*}  al B(*\mathcal{S}) &\rightarrow \bf N\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       omega): X_j(\omega) \in A}. \\end{align}  ( omega): X_j(\omega) \in A}. \\end{align*}    omega): X_j(*\omega) \in A}. \\end{align}  omega, S)&\mapsto {j \leq N  omega): X_j(\omega) \in A}. \\end{align*}  ( omega): X_j(*\omega) \in A}. \\end{align}    omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in S}. omega): X_j(\omega) \in A}. \\end{align}  \\end{align*} omega): X_j(*\omega) \in A}. \\end{align}  \$\$ omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align}  omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align}  omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align}  omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align}  omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align}  omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align} \$\$

```         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          All this now allows us to make sense of the stochastic equation from Remark 2.2.:   \$\$ A_w\^{root=s}(t) = \int\_\mathcal{S}   l eft( A_w\^{root=u}(t - E_i) \bf                                                                               

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1\_{E_i \< t} + \bf 1_{E_i > t}                                                                                                                                                                                                                         



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \right) \dif \xi\_\omega\^s(u) = \$\$   
```
:::

::: {.card title="tableau"}
Probability: theory and examples FPP on IHRGs :=====================================================================================================:+:==================================================================================================:+ Measure space $(S, \mathcal{S}, \mu)$ \$(\mathcal{S} , \mathcal{B}(\mathcal{S}), \tilde{\mu})\$

$A_i$ disjoint $\{u_i\}$ disjoint

$m: \mathcal{S} \to \bf N$, or: \$\x                                                                                                   

```         
                                                                                                    i $m: \Omega    \^  t  s: \mathcal B(\mathcal{S}) \to \bf N$, or:    
```

i

mes \mathcal B(\mathcal{S}) \to \bf N$                                                                          $\xi^s: \Omega \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   t

```         
                                                                                                    i    

                                                                                                    mes \mathcal B(\mathcal{S}) \to \bf N\$    
```

$\mu$ mean-measure of the process, *i.e.*, \$m $\tilde{\mu}$ mean-measure of the process, *i.e.*,\$\xi\^s(

( {

A u

\*i) \stackrel{\mathrel{*\unico                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

 d  i}) \stackrel{\mathrel{\unic                                                                        

 e  o   

 {x2AEB}}}{\sim} P(\mu(A_i)).\$  d   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              e{x2AEB}}}{\sim} P(\tilde{\mu                                                                        

 Here $A_i$ is fixed so $m(A_i)$ is a random variable.  }

```         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          (   
```

We refer to this as the **Poissonian property**.  

```         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {u_i} =\kappa(s, u_i) \mu(u_i))\$   Here $u_i$ is fixed so \$\xi\^s(   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {u_i})\$ is a random variable.   
```

$\mu(A_i) < \infty \implies$ \$ \tilde{\mu}({u_i}) =\kappa(s, u \_ i ) \mu(u_i) \< \infty \implies\$

$\forall \omega \in \Omega$ , the map below is a measure on $\mathcal{S}$. $\forall \omega \in \Omega$ , the map below is a measure on $\mathcal{S}$. $$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $$ \begin{align*}  \begin{align*}    

 m\_{\omega                                                                                              \xi\_\omega\^s\colon \mat                                                                               

 }  h    

    c    

 colon \mathcal{S} &\rightarrow \bf N\                                                                          al B(\mathcal{S}) &\rightarrow \bf N\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

 S&\mapsto m(\omega, S).  S&\mapsto \xi\_(\omega, s).    

 \end{align*} \\end{align\*} $$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $$ Here $\omega$ is fixed, so $m_{\omega}$ is a measure. Here $\omega$ is fixed, so $\xi_\omega^s$ is a measure.

Let us now describe how one can construct such a map $m$. Let us now describe how one can construct such a map $\xi$. Since $\mu(S) < \infty,$ we can define the following probability measure $\nu := \frac{\mu}{\mu(S)}.$ Since \$\tilde{    

                                                                                                             

 We sample $N \sim P(\mu(S))$ independently of everything else.  mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}mu}(\mathcal S) = \sum\_{i=1}\^n We then sample \$X_1, X_2, \do  \kappa(s, u_i) \mu(u_i) \< \infty\$, we can define the following probability measure \$\nu := \f           

 t r

s a

\stackrel{i.i.d}{\sim} \nu\$. c{\tilde\mu}{\tilde\mu(\mathcal{S})}.\$ All this allows us to finally define $m$ via We also sample $N \sim P(\tilde\mu(\mathcal{S}))$ independently of everything else. \$\$ \begin{align*}  We then sample \$X_1, X_2, \do                                                                         

 m\colon \Omega                                                                                         t    

                                                                                                        s    

    \stackrel{i.i.d}{\sim} \nu.\$    

 times \mathcal{S} &\rightarrow \bf N\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

 (  All this allows us to finally define $\xi$ via    

       

 omega, A)&\mapsto {j \leq N  \$\$    

 (  \begin{align*}    

    \xi\colon \Omega \times \mat                                                                          

 omega): X_j(\omega) \in A}.  h    

 \end{align*}  c omega): X_j(\omega) \in A}. \\end{align*}  al B(*\mathcal{S}) &\rightarrow \bf N\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       omega): X_j(\omega) \in A}. \\end{align}  ( omega): X_j(\omega) \in A}. \\end{align*}    omega): X_j(*\omega) \in A}. \\end{align}  omega, S)&\mapsto {j \leq N  omega): X_j(\omega) \in A}. \\end{align*}  ( omega): X_j(*\omega) \in A}. \\end{align}    omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in S}. omega): X_j(\omega) \in A}. \\end{align}  \\end{align*} omega): X_j(*\omega) \in A}. \\end{align}  \$\$ omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align}  omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align}  omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align}  omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align}  omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align}  omega): X_j(\omega) \in A}. \\end{align*}  omega): X_j(*\omega) \in A}. \\end{align} \$\$

```         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          All this now allows us to make sense of the stochastic equation from Remark 2.2.:   \$\$ A_w\^{root=s}(t) = \int\_\mathcal{S}   l eft( A_w\^{root=u}(t - E_i) \bf                                                                               

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1\_{E_i \< t} + \bf 1_{E_i > t}                                                                                                                                                                                                                         



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \right) \dif \xi\_\omega\^s(u) = \$\$   
```
:::
